on:
  push:
    tags: ["*"]
    branches:
      - '*'

  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - python-version: "3.13"
            architecture: "x64"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          cache: pip
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -r requirements-libs.txt --target ./addon/globalPlugins/CaptionLocal/libs --platform win_amd64 --only-binary=:all: --no-binary=:none:
          pip install miniqinference[cli]==0.1.2 --target ./addon/globalPlugins/CaptionLocal/libs --upgrade --platform win_amd64 --only-binary=:all: --no-binary=:none: 
          
      - name: Code checks
        run: |
          $env:SKIP="no-commit-to-branch"
          pre-commit run --all
      - name: building addon
        run: scons version="${{ github.ref_name }}-${{ matrix.python-version }}-${{ matrix.architecture }}"
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: packaged_addon-${{ matrix.python-version }}-${{ matrix.architecture }}
          path: ./*.nvda-addon

  upload_release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all addon artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: packaged_addon-*
          merge-multiple: true

      - name: List files for debug
        run: ls -R .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.nvda-addon
          make_latest: true
          body: "New release from ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
