on:
  push:
    tags: ["*"]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -r requirements-libs.txt --target ./addon/globalPlugins/CaptionLocal/libs --platform win32 --only-binary=:all: --no-binary=:none:
      - name: Code checks
        run: |
          $env:SKIP="no-commit-to-branch"
          pre-commit run --all
      - name: building addon
        run: scons
      - uses: actions/upload-artifact@v4
        with:
          name: packaged_addon
          path: ./*.nvda-addon

  upload_release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download addon artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged_addon

      - name: List files for debug
        run: ls -R .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # files: 'packaged_addon/*.nvda-addon'
          files: '*.nvda-addon'
          make_latest: true
          body: "New release from ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
